required-version = "==0.16.6"
target-version = "py312"
line-length = 100
include = ["*.py", "*.pyi"]
extend-exclude = ["models", "vendor/demucs"]
force-exclude = true

[lint]
select = ["E4", "E7", "E9", "F", "I", "B"]

[lint.per-file-ignores]
"**/__init__.py" = ["F401"]
"core/model_config/config.py" = ["F403", "F405"]
"core/model_data.py" = ["F403", "F405"]
"core/model_repository.py" = ["F403", "F405"]
"engines/*.py" = ["F403", "F405"]

[format]
quote-style = "preserve"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-format = false
