"""Bundled symbolic icon names for the download queue (resources/icons/scalable/actions/)."""

ICON_CANCEL = "stop-small-symbolic"
ICON_CHIP_SUCCESS = "check-round-outline-symbolic"
ICON_CHIP_CANCELLED = "error-outline-symbolic"
ICON_CHIP_PARTIAL = "exclamation-mark-symbolic"
ICON_CHIP_FAILED = "exclamation-mark-symbolic"
ICON_ROW_SUCCESS = "success-small-symbolic"
ICON_CANCELLED = "stop-small-symbolic"
ICON_FAILED = "warning-outline-symbolic"
