"""Bundled symbolic icon names for the download queue (resources/icons/scalable/actions/)."""

ICON_CANCEL = "uvr-stop-small-symbolic"
ICON_CHIP_SUCCESS = "uvr-check-round-outline-symbolic"
ICON_CHIP_CANCELLED = "uvr-error-outline-symbolic"
ICON_CHIP_PARTIAL = "uvr-exclamation-mark-symbolic"
ICON_CHIP_FAILED = "uvr-exclamation-mark-symbolic"
ICON_ROW_SUCCESS = "uvr-success-small-symbolic"
ICON_CANCELLED = "uvr-cross-small-symbolic"
ICON_FAILED = "uvr-warning-outline-symbolic"
ICON_RETRY = "view-refresh-symbolic"
