"""Legacy flat key ↔ nested (section, field) mapping."""

from __future__ import annotations

# flat legacy key → (section, nested field name)
FLAT_TO_PATH: dict[str, tuple[str, str]] = {
    # process
    "chosen_process_method": ("process", "method"),
    "is_gpu_conversion": ("process", "use_gpu"),
    "is_autocast": ("process", "autocast"),
    "is_use_directml": ("process", "use_directml"),
    "device_set": ("process", "device"),
    "is_testing_audio": ("process", "testing_audio"),
    "is_add_model_name": ("process", "add_model_name"),
    "is_accept_any_input": ("process", "accept_any_input"),
    "is_normalization": ("process", "normalization"),
    "is_match_mix_level": ("process", "match_mix_level"),
    "is_prevent_export_clipping": ("process", "prevent_export_clipping"),
    "amplification_threshold": ("process", "amplification_threshold"),
    "is_create_model_folder": ("process", "create_model_folder"),
    "is_auto_update_model_params": ("process", "auto_update_model_params"),
    "save_format": ("process", "save_format"),
    "wav_type_set": ("process", "wav_type"),
    "mp3_bit_set": ("process", "mp3_bitrate"),
    "flac_bit_set": ("process", "flac_bit_depth"),
    "export_path": ("process", "export_path"),
    "input_paths": ("process", "input_paths"),
    "lastDir": ("process", "last_dir"),
    "model_sample_mode": ("process", "sample_mode"),
    "model_sample_mode_duration": ("process", "sample_mode_duration"),
    "long_file_chunk_seconds": ("process", "long_file_chunk_seconds"),
    "long_file_chunk_overlap_seconds": ("process", "long_file_chunk_overlap_seconds"),
    "semitone_shift": ("process", "semitone_shift"),
    "user_code": ("process", "user_code"),
    "model_hash_table": ("process", "model_hash_table"),
    "set_vocal_splitter": ("process", "vocal_splitter"),
    "is_set_vocal_splitter": ("process", "vocal_splitter_enabled"),
    "is_save_inst_set_vocal_splitter": ("process", "save_inst_vocal_splitter"),
    "is_deverb_vocals": ("process", "deverb_vocals"),
    "deverb_vocal_opt": ("process", "deverb_vocal_opt"),
    "voc_split_save_opt": ("process", "voc_split_save_opt"),
    # vr
    "vr_model": ("vr", "model"),
    "aggression_setting": ("vr", "aggression_setting"),
    "window_size": ("vr", "window_size"),
    "batch_size": ("vr", "batch_size"),
    "crop_size": ("vr", "crop_size"),
    "is_tta": ("vr", "is_tta"),
    "is_output_image": ("vr", "is_output_image"),
    "is_post_process": ("vr", "is_post_process"),
    "is_high_end_process": ("vr", "is_high_end_process"),
    "post_process_threshold": ("vr", "post_process_threshold"),
    "vr_voc_inst_secondary_model": ("vr", "voc_inst_secondary_model"),
    "vr_other_secondary_model": ("vr", "other_secondary_model"),
    "vr_bass_secondary_model": ("vr", "bass_secondary_model"),
    "vr_drums_secondary_model": ("vr", "drums_secondary_model"),
    "vr_is_secondary_model_activate": ("vr", "is_secondary_model_activate"),
    "vr_voc_inst_secondary_model_scale": ("vr", "voc_inst_secondary_model_scale"),
    "vr_other_secondary_model_scale": ("vr", "other_secondary_model_scale"),
    "vr_bass_secondary_model_scale": ("vr", "bass_secondary_model_scale"),
    "vr_drums_secondary_model_scale": ("vr", "drums_secondary_model_scale"),
    # mdx
    "mdx_net_model": ("mdx", "model"),
    "mdx_segment_size": ("mdx", "segment_size"),
    "overlap_mdx": ("mdx", "overlap_mdx"),
    "overlap_mdx23": ("mdx", "overlap_mdx23"),
    "is_chunk_mdxnet": ("mdx", "is_chunk_mdxnet"),
    "is_mdx23_combine_stems": ("mdx", "is_mdx23_combine_stems"),
    "is_mdx_include_stem_complement": ("mdx", "is_mdx_include_stem_complement"),
    "chunks": ("mdx", "chunks"),
    "margin": ("mdx", "margin"),
    "compensate": ("mdx", "compensate"),
    "is_denoise": ("mdx", "is_denoise"),
    "denoise_option": ("mdx", "denoise_option"),
    "phase_option": ("mdx", "phase_option"),
    "phase_shifts": ("mdx", "phase_shifts"),
    "is_save_align": ("mdx", "is_save_align"),
    "is_match_frequency_pitch": ("mdx", "is_match_frequency_pitch"),
    "is_match_silence": ("mdx", "is_match_silence"),
    "is_spec_match": ("mdx", "is_spec_match"),
    "is_mdx_c_seg_def": ("mdx", "is_mdx_c_seg_def"),
    "is_invert_spec": ("mdx", "is_invert_spec"),
    "is_mixer_mode": ("mdx", "is_mixer_mode"),
    "mdx_batch_size": ("mdx", "batch_size"),
    "mdx_voc_inst_secondary_model": ("mdx", "voc_inst_secondary_model"),
    "mdx_other_secondary_model": ("mdx", "other_secondary_model"),
    "mdx_bass_secondary_model": ("mdx", "bass_secondary_model"),
    "mdx_drums_secondary_model": ("mdx", "drums_secondary_model"),
    "mdx_is_secondary_model_activate": ("mdx", "is_secondary_model_activate"),
    "mdx_voc_inst_secondary_model_scale": ("mdx", "voc_inst_secondary_model_scale"),
    "mdx_other_secondary_model_scale": ("mdx", "other_secondary_model_scale"),
    "mdx_bass_secondary_model_scale": ("mdx", "bass_secondary_model_scale"),
    "mdx_drums_secondary_model_scale": ("mdx", "drums_secondary_model_scale"),
    "mdx_stems": ("mdx", "stems"),
    "mdx_stems_selected": ("mdx", "stems_selected"),
    # demucs
    "demucs_model": ("demucs", "model"),
    "segment": ("demucs", "segment"),
    "overlap": ("demucs", "overlap"),
    "shifts": ("demucs", "shifts"),
    "chunks_demucs": ("demucs", "chunks_demucs"),
    "margin_demucs": ("demucs", "margin_demucs"),
    "is_chunk_demucs": ("demucs", "is_chunk_demucs"),
    "is_split_mode": ("demucs", "is_split_mode"),
    "is_demucs_combine_stems": ("demucs", "is_demucs_combine_stems"),
    "demucs_voc_inst_secondary_model": ("demucs", "voc_inst_secondary_model"),
    "demucs_other_secondary_model": ("demucs", "other_secondary_model"),
    "demucs_bass_secondary_model": ("demucs", "bass_secondary_model"),
    "demucs_drums_secondary_model": ("demucs", "drums_secondary_model"),
    "demucs_is_secondary_model_activate": ("demucs", "is_secondary_model_activate"),
    "demucs_voc_inst_secondary_model_scale": ("demucs", "voc_inst_secondary_model_scale"),
    "demucs_other_secondary_model_scale": ("demucs", "other_secondary_model_scale"),
    "demucs_bass_secondary_model_scale": ("demucs", "bass_secondary_model_scale"),
    "demucs_drums_secondary_model_scale": ("demucs", "drums_secondary_model_scale"),
    "demucs_stems": ("demucs", "stems"),
    "demucs_pre_proc_model": ("demucs", "pre_proc_model"),
    "is_demucs_pre_proc_model_activate": ("demucs", "is_pre_proc_model_activate"),
    "is_demucs_pre_proc_model_inst_mix": ("demucs", "is_pre_proc_model_inst_mix"),
    # ensemble (four keys absent from DEFAULT_DATA but used by UI)
    "ensemble_main_stem": ("ensemble", "main_stem"),
    "ensemble_type": ("ensemble", "type"),
    "selected_models": ("ensemble", "selected_models"),
    "chosen_ensemble": ("ensemble", "chosen_ensemble"),
    "is_save_all_outputs_ensemble": ("ensemble", "save_all_outputs"),
    "is_append_ensemble_name": ("ensemble", "append_ensemble_name"),
    "is_wav_ensemble": ("ensemble", "wav_ensemble"),
    "is_cleanup_ensemble_temps": ("ensemble", "cleanup_temps"),
    # audio tools
    "chosen_audio_tool": ("audio_tools", "chosen_audio_tool"),
    "choose_algorithm": ("audio_tools", "choose_algorithm"),
    "time_stretch_rate": ("audio_tools", "time_stretch_rate"),
    "pitch_rate": ("audio_tools", "pitch_rate"),
    "apollo_overlap": ("audio_tools", "apollo_overlap"),
    "apollo_chunk_size": ("audio_tools", "apollo_chunk_size"),
    "apollo_model": ("audio_tools", "apollo_model"),
    "is_time_correction": ("audio_tools", "is_time_correction"),
    "time_window": ("audio_tools", "time_window"),
    "intro_analysis": ("audio_tools", "intro_analysis"),
    "db_analysis": ("audio_tools", "db_analysis"),
    "fileOneEntry": ("audio_tools", "file_one_entry"),
    "fileOneEntry_Full": ("audio_tools", "file_one_entry_full"),
    "fileTwoEntry": ("audio_tools", "file_two_entry"),
    "fileTwoEntry_Full": ("audio_tools", "file_two_entry_full"),
    "DualBatch_inputPaths": ("audio_tools", "dual_batch_input_paths"),
    # ui
    "color_scheme": ("ui", "color_scheme"),
    "window_width": ("ui", "window_width"),
    "window_height": ("ui", "window_height"),
    "window_maximized": ("ui", "window_maximized"),
    "notify_process_complete": ("ui", "notify_process_complete"),
    "notify_process_failed": ("ui", "notify_process_failed"),
    "confirm_processing_plan": ("ui", "confirm_processing_plan"),
    "notify_download_complete": ("ui", "notify_download_complete"),
    "notify_download_failed": ("ui", "notify_download_failed"),
}

PATH_TO_FLAT: dict[tuple[str, str], str] = {
    path: flat_key for flat_key, path in FLAT_TO_PATH.items()
}
