"""Structural widget interfaces used by framework-light UI helpers."""

from __future__ import annotations

from enum import Enum, auto
from typing import TYPE_CHECKING, Protocol, Sequence, Tuple

if TYPE_CHECKING:
    from gi.repository import Adw, Gtk

    from core.audio_plan import AudioJobSpec, ResolvedAudioJob
    from core.job_callbacks import JobCallbacks
    from core.job_plan import JobSpec, ResolvedJob
    from core.model_repository import ModelRepository

    from .run_error_context import RunErrorContext

from core.settings import Settings


class InputPathsRow(Protocol):
    def set_paths(self, paths: Sequence[str], notify: bool = ...) -> None: ...


class OutputPathRow(Protocol):
    def set_path(self, path: str, notify: bool = ...) -> None: ...


class SwitchRow(Protocol):
    # Positional-only: Adw.SwitchRow names this parameter ``is_active``, and a
    # protocol with a named parameter would not match it structurally.
    def set_active(self, active: bool, /) -> None: ...


class SampleModeRow(Protocol):
    def set_title(self, title: str) -> None: ...

    def set_subtitle(self, subtitle: str) -> None: ...

    def set_active(self, active: bool, /) -> None: ...


class WindowSizing(Protocol):
    """The bit of ``Gtk.Window`` that dialog sizing actually needs.

    Typing against this rather than ``Gtk.Window`` lets the sizing tests pass a
    two-method fake instead of constructing a real window.
    """

    def get_width(self) -> int: ...

    def get_default_size(self) -> Tuple[int, int]: ...


class FormatRow(Protocol):
    def apply_from_settings(self, settings: Settings) -> None: ...


class FormatEdit(Enum):
    FORMAT = auto()
    QUALITY = auto()


class VocalSplitEdit(Enum):
    ENABLED = auto()
    MODEL = auto()
    SAVE_INSTRUMENTALS = auto()
    DEVERB = auto()
    DEVERB_OPTION = auto()


class ReadableInputPathsRow(Protocol):
    @property
    def paths(self) -> Sequence[str]: ...


class ReadableOutputPathRow(Protocol):
    @property
    def path(self) -> str: ...


class ReadableSwitchRow(Protocol):
    def get_active(self) -> bool: ...


class ReadableFormatRow(Protocol):
    @property
    def save_format(self) -> str: ...

    @property
    def quality_value(self) -> str: ...


class ReadableVocalSplitRow(Protocol):
    @property
    def enabled(self) -> bool: ...

    @property
    def model_value(self) -> str: ...

    @property
    def model_write_allowed(self) -> bool: ...

    @property
    def save_instrumentals(self) -> bool: ...

    @property
    def deverb(self) -> bool: ...

    @property
    def deverb_option(self) -> str: ...


class RunReadiness(Protocol):
    def start_blocked_reason(self) -> str | None: ...


class RunTarget(Protocol):
    """A processing surface owns its worker and diagnostic inputs."""
    @property
    def error_key(self) -> str: ...
    @property
    def run_label(self) -> str: ...
    def start_blocked_reason(self) -> str | None: ...
    def build_job_spec(self) -> JobSpec | AudioJobSpec: ...
    def start(self, callbacks: JobCallbacks, plan: ResolvedJob | ResolvedAudioJob | None = None) -> None: ...
    def stop(self) -> None: ...
    def pause(self) -> None: ...
    def unpause(self) -> None: ...
    def worker_is_running(self) -> bool: ...
    def snapshot_error_context(self) -> RunErrorContext: ...
    def bind_run_settings(self, settings: Settings) -> None: ...


class RunHost(Protocol):
    """Run presentation and application operations, without page/widget inspection."""
    @property
    def settings(self) -> Settings: ...
    @property
    def repo(self) -> ModelRepository: ...
    @property
    def target(self) -> RunTarget | None: ...
    @property
    def context_target(self) -> RunTarget: ...
    @property
    def dialog_parent(self) -> Gtk.Window: ...
    @property
    def fallback_error_key(self) -> str: ...
    def get_application(self) -> Gtk.Application | None: ...
    def toast(self, message: str) -> None: ...
    def add_toast(self, toast: Adw.Toast) -> None: ...
    def set_pulse(self, active: bool) -> None: ...
    def append_console(self, text: str) -> None: ...
    def clear_console(self) -> None: ...
    def set_progress_text(self, text: str) -> None: ...
    def set_progress_fraction(self, fraction: float) -> None: ...
    def clear_progress(self) -> None: ...
    def set_run_label(self, label: str) -> None: ...
    def mark_run_complete(self) -> None: ...
    def reveal_log(self) -> None: ...
    def prepare_log(self) -> None: ...
    def start_enabled(self) -> bool: ...
    def stop_enabled(self) -> bool: ...
    def enable_start(self, enabled: bool) -> None: ...
    def enable_stop(self, enabled: bool) -> None: ...
    def start_label(self) -> str | None: ...
    def set_start_label(self, label: str) -> None: ...
    def describe_start(self, description: str) -> None: ...
    def refresh_readiness(self) -> None: ...
    def set_options_sensitive(self, sensitive: bool) -> None: ...
    def set_edit_actions_sensitive(self, sensitive: bool) -> None: ...
    def bind_run_settings(self, settings: Settings) -> None: ...
    def restore_runner_settings(self) -> None: ...
    def run_output_dir(self) -> str: ...
    def exported_after_oom(self) -> bool: ...
    def active_download_count(self) -> int: ...
    def stop_context_workers(self, *, force: bool = False) -> None: ...
    def stop_all_workers(self, *, force: bool = False) -> None: ...
    def destroy(self) -> None: ...
    def release_inference_memory(self, *, wait_for_stop: float = 0.0, force_if_alive: bool = False, clear_weight_cache: bool = False, park_weights: bool = False) -> None: ...
